config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :cocktails, only: [:index, :show, :new, :create] do
    # resources :ingredients, only: [:index, :show]
    resources :doses, only: [:new, :create]
    # new_cocktail_dose GET    /cocktails/:cocktail_id/doses/new(.:format)
  end
  resources :doses, only: :destroy

  root to: 'cocktails#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true
  has_one_attached :photo
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :ingredient, presence: true, uniqueness: { scope: :cocktail, message:
  'should create only one dose per cocktail and ingredient' }
  validates :description, presence: true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show]

  def index
    @cocktails = Cocktail.all
  end

  def new
    @cocktail = Cocktail.new
  end

  def show; end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail), notice: 'Cocktail was successfully created.'
    else
      render :new
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    # cocktail id dans l'url
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail), notice: 'Dose was successfully added to the cocktail.'
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @cocktail = @dose.cocktail
    @dose.destroy
    redirect_to cocktail_path(@cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end


def destroy
  @review = Review.find(params[:id])
  restaurant = @review.restaurant
  @review.destroy
  redirect_to restaurant_path(restaurant)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for(@cocktail) do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit "Save", class: "btn btn-primary" %>
<% end %>

app/views/cocktails/index.html.erb
<div class="bg" style="background-image: linear-gradient(90deg, rgba(2,0,36,1) 0%, rgba(2,0,36,0.16710434173669464) 0%), url('../assets/images/vice-city-bg.jpg');">

<pre>
 _    ______             _______ __
| |  / /  _/_______     / ____(_) /___  __
| | / // // ___/ _ \   / /   / / __/ / / /
| |/ // // /__/  __/  / /___/ / /_/ /_/ /
|___/___/\___/\___/   \____/_/\__/\__, /
   ______           __   __      /____/
  / ____/___  _____/ /__/ /_____ _(_) /____
 / /   / __ \/ ___/ //_/ __/ __ `/ / / ___/
/ /___/ /_/ / /__/ , // /_/ /_/ / / (__  )
\____/\____/\___/_/|_|\__/\__,_/_/_/____/

  </pre>
  <div class="add-link"> <%= link_to 'add a new cocktail', new_cocktail_path %></div>
</div>



<div class="big-container d-flex justify-content-center">

<div class="cocktails-container">

<% @cocktails.each do |cocktail| %>
  <div class="card-product">
    <% if cocktail.photo.attached? %>
      <%= cl_image_tag cocktail.photo.key, height: 300, width: 400, crop: :fill %>
    <% else %>
      <img src='https://source.unsplash.com/weekly?cocktail'/>
    <% end %>
    <div class="card-product-infos">
      <h2><%= cocktail.name.upcase%></h2>
      <p><%= link_to 'show cocktail', cocktail_path(cocktail) %></p>
    </div>
  </div>
<% end %>

<img src="../assets/images/vice-city-bg" alt="vc">

 </div>
</div>

app/views/cocktails/new.html.erb
<%= render "form", cocktail: @cocktail %>

app/views/cocktails/show.html.erb
<h1><%= @cocktail.name %> </h1>
<%  @cocktail.doses.each do |dose|%>
<p> <%= dose.description %> / <%= dose.ingredient.name %></p>
<%= link_to ' - Remove an ingredient', dose_path(dose), method: :delete, data: { confirm: 'Are you sure?' } %><br>
  <% end %>

<% if @cocktail.photo.attached? %>
   <%= cl_image_tag @cocktail.photo.key, height: 300, with:400, crop: :fill %> <br>
<% end %>

<%= link_to '+ Add a new ingredient/dose to the cocktail', new_cocktail_dose_path(@cocktail) %><br>
<%= link_to 'Go back to cocktails', cocktails_path %>

<!-- DELETE /cocktails/:cocktail_id/doses/:id(.:format)   -->

app/views/doses/new.html.erb
<%= simple_form_for([@cocktail, @dose]) do |f| %>
  <%= f.input :description %>
  <%= f.association :ingredient %>
  <!-- f.association fait une liste de tous les ingredients puis enregistrera l'id de l'ingredient une fois selectionné -->
  <%= f.submit "Submit ingredient/dose" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ViceCityCocktails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <body>
      <%= yield %>
  </body>